# Generated by Django 4.0.2 on 2022-02-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('ano', models.IntegerField()),
                ('data', models.DateField()),
                ('unidade_saude', models.CharField(default='HMTLQS', max_length=100)),
            ],
            options={
                'verbose_name': 'Prontuario Familiar',
                'verbose_name_plural': 'Prontuarios',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dt_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('logradouro', models.CharField(max_length=100)),
                ('num_endereco', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('ponto_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prontuario_Familiar.prontuario')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('parentesco', models.CharField(max_length=50)),
                ('dt_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('Feminino', 'FEMININO'), ('Masculino', 'MASCULINO'), ('Ignorado', 'IGNORADO')], default='', max_length=20)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado(a)', 'CASADO(A)'), ('Divorciado(a)', 'DIVORCIADO(A)'), ('Separado(a)', 'SEPARADO(A)'), ('Solteiro(a)', 'SOLTEIRO(A)'), ('União Estável(a)', 'UNIÃO ESTÁVEL(A)'), ('Viúvo(a)', 'VIÚVO(A)'), ('Outro', 'OUTRO')], default='', max_length=50)),
                ('naturalidade', models.CharField(max_length=20)),
                ('escolaridade', models.CharField(blank=True, choices=[('Abalfabeto', 'ANALFABETO'), ('Fundamental Incompleto', 'FUNDAMENTAL INCOMPLETO'), ('Fundamental Completo', 'FUNDAMENTAL COMPLETO'), ('Médio Incompleto', 'MÉDIO INCOMPLETO'), ('Médio Completo', 'MÉDIO COMPLETO'), ('Superior Incompleto', 'SUPERIOR INCOMPLETO'), ('Superior Completo', 'SUPERIOR COMPLETO'), ('Pós-graduação Incompleto', 'PÓS-GRADUAÇÃO INCOMPLETO'), ('Pós-graduação Completo', 'PÓS-GRADUAÇÃO COMPLETO')], default='', max_length=50)),
                ('ativ_economica', models.CharField(max_length=50)),
                ('renda', models.FloatField(blank=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prontuario_Familiar.responsavel')),
            ],
            options={
                'verbose_name': 'Grupo Familiar',
                'verbose_name_plural': 'GruposFamiliares',
            },
        ),
    ]
