# Generated by Django 4.0.2 on 2022-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prontuario_Familiar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
