# Generated by Django 4.0.2 on 2022-02-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prontuario_Familiar', '0002_alter_grupofamiliar_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='ano',
        ),
    ]
