# Generated by Django 4.0.2 on 2022-02-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prontuario_Familiar', '0003_remove_prontuario_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupofamiliar',
            old_name='nome',
            new_name='nome_integrante',
        ),
    ]
