# Generated by Django 4.0.2 on 2022-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prontuario_Familiar', '0006_alter_grupofamiliar_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupofamiliar',
            name='renda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
